apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - prod.yaml
    path: helm/demo-app
    repoURL: https://github.com/MSFT-MCSEMEA-Demo/argocd-apps-config
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true  
