apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}
  ports: 
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.container.port }}