name: DemoApp Deployment
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "argoCD app environment"
        type: choice
        default: "dev"
        options:
          - "dev"
          - "prod"
      name:
        type: string
        description: "ArgoCD App name"
        default: "demoapp"    
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  Deploy_DemoApp:    
    runs-on: ubuntu-latest        
    environment: 
      name: '${{ github.event.inputs.name }}_${{ github.event.inputs.environment }}' 
      url: ${{ steps.argoapp.outputs.url }}   
    steps:  
    - name: Checkout source code 
      uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Get Resource Group and AKS names
      id: getrgaks
      run: |
        if [[ '${{ github.event.inputs.environment }}' == 'dev' ]]; then
          echo "rgname=$(cat global/rg-dev)" >> $GITHUB_OUTPUT 
          echo "aksname=$(cat global/aks-dev)" >> $GITHUB_OUTPUT        
        else
          echo "rgname=$(cat global/rg-prod)" >> $GITHUB_OUTPUT 
          echo "aksname=$(cat global/aks-prod)" >> $GITHUB_OUTPUT        
        fi    
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with: 
        resource-group: '${{ steps.getrgaks.outputs.rgname }}' 
        cluster-name: '${{ steps.getrgaks.outputs.aksname }}'
    - name: Deploy ArgoCD DemoApp
      id: argoapp
      run: |
        kubectl apply -n argocd -f ./argoCD-apps/demo-app/argocd-app-${{ github.event.inputs.environment }}.yaml        
        sleep 30
        echo "url=http://$(kubectl get svc ${{ github.event.inputs.name }}-svc -n ${{ github.event.inputs.name }}  -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT          
